a = input('digite algo ')
print('Essa valor é alpha numérico ? {}'.format(a.isalnum()))
print('Essa valor é alpha? {}'.format(a.isalpha()))
print('Essa valor é numérico ? {}'.format(a.isnumeric()))
print('Essa valor está captlizado ? {}'.format(a.istitle()))
print('Essa valor está em maiusculo ? {}'.format(a.isupper()))
print('Essa valor está em minusculo ? {}'.format(a.islower()))